api_platform:
    title: 'Bdex Api'
    description: 'Manage and provide data of artists'
    version: '1'
    mapping:
        paths:       ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/config/api_platform/resources']
    swagger:
        versions: [3]
    collection:
        pagination:
            items_per_page: 12
    patch_formats:
        json:     ['application/merge-patch+json']
    formats:
        jsonld:      ['application/ld+json']
        jsonapi:     ['application/vnd.api+json']
        json:        ['application/json']
        xml:         ['application/xml', 'text/xml']
        yaml:        ['application/x-yaml']
        csv:         ['text/csv']
        html:        ['text/html']
