# config/routes.yaml
controllers:
    resource: '../src/Controller/'
    type:     annotation

ArtistsBundle:
    resource: '../src/ArtistsBundle/Controller'
    type:     annotation

GroupsBundle:
    resource: '../src/GroupsBundle/Controller'
    type:     annotation

AdminBundle:
    resource: '../src/AdminBundle/Controller'
    type:     annotation

SecurityBundle:
    resource: '../src/SecurityBundle/Controller'
    type:     annotation
