# config/routes.yaml
controllers:
    resource: '../src/Controller/'
    type:     annotation

ArtistsBundle:
    resource: '../src/ArtistsBundle/Controller'
    type:     annotation

GroupsBundle:
    resource: '../src/GroupsBundle/Controller'
    type:     annotation

AppAdminBundle:
    resource: '../src/AdminBundle/App/Controller'
    type:     annotation

ApiAdminBundle:
    resource: '../src/AdminBundle/Api/Controller'
    type:     annotation

SecurityBundle:
    resource: '../src/SecurityBundle/Controller'
    type:     annotation

